# Generated by Django 6.0.8 on 2026-09-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem_samples', '0053_intercolumn_value_controller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemsample',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
