# Generated by Django 6.0.8 on 2026-09-25 18:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_default_definition(apps, schema_editor):
    definition = apps.get_model('problem_samples', 'OldTicketDefinition')
    definition.objects.using(schema_editor.connection.alias).get_or_create(
        pk=1, defaults={'age_months': 24},
    )


class Migration(migrations.Migration):

    dependencies = [
        ('problem_samples', '0063_automatic_disposal_expiry_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OldTicketDefinition',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('age_months', models.PositiveSmallIntegerField(default=24, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1200)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_ticket_definitions_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'problem_samples_old_ticket_definition',
            },
        ),
        migrations.RunPython(create_default_definition, migrations.RunPython.noop),
    ]
