# Generated by Django 6.0.8 on 2026-09-25 18:57

from django.conf import settings
from django.db import migrations, models


def add_testing_workflow_and_detach_finished(apps, schema_editor):
    Column = apps.get_model('problem_samples', 'ProblemColumn')
    Sample = apps.get_model('problem_samples', 'ProblemSample')
    db = schema_editor.connection.alias
    pending = 'To be back to testing'
    finished = {'Shipped back to client', 'Back to testing'}
    for column in Column.objects.using(db).filter(field_key='current-workflow').iterator():
        choices = [choice for choice in (column.choices or []) if choice != pending]
        before = choices.index('Back to testing') if 'Back to testing' in choices else len(choices)
        choices.insert(before, pending)
        column.choices = choices
        column.save(update_fields=['choices'])

    for sample in Sample.objects.using(db).filter(container__isnull=False).only(
        'id', 'current_workflow', 'custom_values'
    ).iterator():
        chosen = (sample.custom_values or {}).get('current-workflow')
        workflow = chosen if chosen in finished else sample.current_workflow
        if workflow in finished:
            Sample.objects.using(db).filter(pk=sample.pk).update(container=None, current_workflow=workflow)


class Migration(migrations.Migration):

    dependencies = [
        ('problem_samples', '0064_old_ticket_definition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(add_testing_workflow_and_detach_finished, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='problemsample',
            constraint=models.CheckConstraint(condition=models.Q(('container__isnull', True), models.Q(('current_workflow__in', ['Shipped back to client', 'Back to testing']), _negated=True), _connector='OR'), name='no_container_for_shipped_or_testing'),
        ),
    ]
